### ISSUE TITLE
get_query_comment doesn't work with dbt 1.5 metadata changes

### ISSUE THREAD

**Issue by sp-tkerlavage** [get-select/dbt-snowflake-query-tags#10]
>To support model versions, the type of refs has changed from List[List[str]] to List[RefArgs], with nested keys name: str, package: Optional[str] = None, and version: Union[str, float, NoneType] = None).

https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.5#for-consumers-of-dbt-artifacts-metadata

The implementation of get_query_comment has

```
        {%- if node.resource_type != ('seed') -%} {# Otherwise this throws an error saying 'Seeds cannot depend on other nodes.' #}
            {%- if node.refs is defined -%}
                {% set refs = [] %}
                {% for ref in node.refs %}
                    {%- do refs.append(ref[0]) -%}
                {% endfor %}
                {%- do comment_dict.update(
                    node_refs=refs | unique | list
                ) -%}
            {%- endif -%}
        {%- endif -%}
```

`{%- do refs.append(ref[0]) -%}` will no longer work in dbt 1.5. This now works instead `{%- do refs.append(ref.name) -%}`

**Comment by NiallRees** [comment]
Thanks for both raising and sharing the solution @sp-tkerlavage !
