### ISSUE TITLE
Question: Why not including the rest of the model properties in the query tags?

### ISSUE THREAD

**Issue by ibardarov-fms** [get-select/dbt-snowflake-query-tags#12]
Hello,
I  noticed that in the previous version of the plugin, the query tags had more information available. However,  it seems that all the items related to query tags have been removed.  

https://github.com/get-select/dbt-snowflake-query-tags/pull/8/files

I'm curious to understand the rationale behind this decision. Specifically, I would like to know why the plugin no longer includes the remaining properties from the dbt model in the query tags. Is it because of limitations such as the size limit of the query tags?

``` 
    {# We have to bring is_incremental through here because its not available in the comment context #}
    {% if model.resource_type == 'model' %}
        {%- do tag_dict.update(
            is_incremental=is_incremental()
        ) -%}


>>> 
        {%- do tag_dict.update(
            model_name=model.name
        ) -%}
        {%- do tag_dict.update(
            model_alias=model.alias
        ) -%}
        {%- do tag_dict.update(
            model_schema=model.schema
        ) -%}
.............
<<<
    {% endif %}
```

**Comment by ian-whitestone** [comment]
hey @ibardarov-fms, 

> Is it because of limitations such as the size limit of the query tags?

this is why we moved everything into the query comment - we were running into the 2000 character limit.

however, we couldn't move everything. the  `is_incremental` indicator has to live in the query tag because it is available at runtime when the query comment is being generated by dbt.
