### ISSUE TITLE
Allow tags to be selectable?

### ISSUE THREAD

**Issue by gary-beautypie** [get-select/dbt-snowflake-query-tags#7]
Just wondered your thoughts on this?
My main reason being issues when bumping up the dbt-snowflake-monitoring package, and the query_tags are v useful for digging into costs, but when coupled with things like dbt_expectactions, or dbt_utils, or anything that generates long node_names/ node_ids I'm exceeding the query_tag size limit in Snowflake.
Also open to any other suggestions you might have on this kinda thing in Snowflake tags 😸

**Comment by NiallRees** [comment]
Hey @gary-beautypie thanks for raising this. Have you got an example full length query tag, node_name or node_id you can share which is exceeding the limit?

**Comment by GtheSheep** [comment]
Hey @NiallRees - sure, full tag would be something like:
```
'{"dbt_snowflake_query_tags_version": "1.1.3", "app": "dbt", "dbt_version": "1.3.0", "project_name": "dbt", "target_name": "default", "target_database": "DATABASE", "target_schema": "PUBLIC", "invocation_id": "3eced1d6-ea04-4456-bae1-5eee3f9edfd0", "node_name": "dbt_expectations_source_expect_table_columns_to_match_ordered_list_HCL_ORDERITEMS_ORDERITEMS_ID__STOREENT_ID__ORDERS_ID__TERMCOND_ID__TRADING_ID__ITEMSPC_ID__CATENTRY_ID__PARTNUM__SHIPMODE_ID__FFMCENTER_ID__MEMBER_ID__ADDRESS_ID__ALLOCADDRESS_ID__PRICE__LINEITEMTYPE__STATUS__OUTPUTQ_ID__INVENTORYSTATUS__LASTCREATE__LASTUPDATE__FULFILLMENTSTATUS__LASTALLOCUPDATE__OFFER_ID__TIMERELEASED__TIMESHIPPED__CURRENCY__COMMENTS__TOTALPRODUCT__QUANTITY__TAXAMOUNT__TOTALADJUSTMENT__SHIPTAXAMOUNT__ESTAVAILTIME__FIELD1__DESCRIPTION__FIELD2__ALLOCATIONGROUP__SHIPCHARGE__BASEPRICE__BASECURRENCY__TRACKNUMBER__TRACKDATE__PREPAREFLAGS__CORRELATIONGROUP__PROMISEDAVAILTIME__SHIPPINGOFFSET__NEEDEDQUANTITY__ALLOCQUANTITY__ALLOCFFMC_ID__ORDRELEASENUM__CONFIGURATIONID__SUPPLIERDATA__SUPPLIERPARTNUMBER__AVAILQUANTITY__ISEXPEDITED__OPTCOUNTER__REQUESTEDSHIPDATE__TIECODE", "node_alias": "dbt_expectations_source_expect_ceccb83baf0faa2df59414b14c1e2086", "node_package_name": "analytics", "node_original_file_path": "models/sources/hcl/sources.yml", "node_database": "PREP", "node_schema": "DBT_TEST_FAILURES", "node_id": "test.analytics.dbt_expectations_source_expect_table_columns_to_match_ordered_list_HCL_ORDERITEMS_ORDERITEMS_ID__STOREENT_ID__ORDERS_ID__TERMCOND_ID__TRADING_ID__ITEMSPC_ID__CATENTRY_ID__PARTNUM__SHIPMODE_ID__FFMCENTER_ID__MEMBER_ID__ADDRESS_ID__ALLOCADDRESS_ID__PRICE__LINEITEMTYPE__STATUS__OUTPUTQ_ID__INVENTORYSTATUS__LASTCREATE__LASTUPDATE__FULFILLMENTSTATUS__LASTALLOCUPDATE__OFFER_ID__TIMERELEASED__TIMESHIPPED__CURRENCY__COMMENTS__TOTALPRODUCT__QUANTITY__TAXAMOUNT__TOTALADJUSTMENT__SHIPTAXAMOUNT__ESTAVAILTIME__FIELD1__DESCRIPTION__FIELD2__ALLOCATIONGROUP__SHIPCHARGE__BASEPRICE__BASECURRENCY__TRACKNUMBER__TRACKDATE__PREPAREFLAGS__CORRELATIONGROUP__PROMISEDAVAILTIME__SHIPPINGOFFSET__NEEDEDQUANTITY__ALLOCQUANTITY__ALLOCFFMC_ID__ORDRELEASENUM__CONFIGURATIONID__SUPPLIERDATA__SUPPLIERPARTNUMBER__AVAILQUANTITY__ISEXPEDITED__OPTCOUNTER__REQUESTEDSHIPDATE__TIECODE.c8cdb46757", "node_resource_type": "test", "materialized": "test", "is_incremental": false, "node_refs": []}'
```
to be honest this type of test isn't super important to my use case but figured I'd just raise in case it came up in other places

**Comment by NiallRees** [comment]
Yikes that's a long node name. The `node_name` portion is pretty integral to the query tag. Given that, I think the best solve is to truncate the `node_name` and `node_id` where necessary by checking the length of the query tag before returning it. What do you think?

**Comment by GtheSheep** [comment]
Yeah I shuddered at it a little 😅 I'm not sure how either of those fields get consumed downstream right now but that sounds fairly reasonable?

**Comment by NiallRees** [comment]
The fields can be used to identify queries to a node_name or node_id, or to group by them to roll up costs to a specific node.

**Comment by GtheSheep** [comment]
🤦 ofc... In this case, even with truncation it'd be pretty unlikely to have 2 nodes that end up with the same name

**Comment by NiallRees** [comment]
Right. Let me know if you're down to take it on!

**Comment by GtheSheep** [comment]
I was too slow! Thanks @NiallRees 🎉
